
services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5436:5432" 
    volumes:
      - wallet_data:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:latest
    restart: always
    ports:
      - "6400:6379"

  typesense:
    image: typesense/typesense:0.25.1
    container_name: typesense
    ports:
      - "8108:8108"
    volumes:
      - typesense_data:/data
    environment:
      TYPESENSE_API_KEY: "supersecurekey"
      TYPESENSE_DATA_DIR: "/data"
      TYPESENSE_SERVER_PORT: "8108"
      TYPESENSE_LOG_LEVEL: "info"
    command: >
      --data-dir /data
      --api-key supersecurekey
      --enable-cors
      --listen-port 8108
    restart: unless-stopped

  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8088:8088"
    env_file:
      - .env
    environment:
    - GOOSE_DBSTRING=postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}?sslmode=disable
    - CACHE_DSN=valkey://valkey:6379/0
    - ES_DSN=http://elasticsearch:9200
    - RAZORPAY_ID=${RAZORPAY_ID}
    - RAZORPAY_SECRET=${RAZORPAY_SECRET}
    - RAZORPAY_WEBHOOK_SECRET=${RAZORPAY_WEBHOOK_SECRET}
    depends_on:
      - db
      - valkey 
      - typesense
    volumes:
      - .:/app

volumes:
  wallet_data:
  typesense_data:

